### ISSUE TITLE
Time Cost: Error from Ref/Assembly detection mode: repDet2nd.Index: 0, Size: 0

### ISSUE THREAD

**Issue by zhangwenda0518** [Xingyu-Liao/LongRepMarker_v2.0#1]
Dear Dr. Liao：
i am sorry to disturb，
when i run 
java LongRepMarker -r ~/test-2021/10.resoult/genome_hic/final_Hic.fasta -o out  -t 120 

**occurred**

Step04: Finding overlap sequences between reference sequences / assemblies [ Time Cost: Error from Ref/Assembly detection mode: repDet2nd.Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at CoreModules.repDet2nd(CoreModules.java:110)
        at threadLTR.run(threadLTR.java:44)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

After monitoring for a period of time,about 4 hours，no longer  commands running in  **top**  monitoring .

And，I found the     **ovlp.paf**    in the ~/LongRepMarker_v2.0-master/alignment    is empty ，Is it related to it?

how can i do;any others information  need?
thanks for your reply!
![image](https://user-images.githubusercontent.com/77140740/158343422-d3d09269-7024-4c43-8526-d6db144899f5.png)

**Comment by Xingyu-Liao** [comment]
Hi  Wenda,

The problem may be caused by too few sequences and too many threads.
Please reduce the number of threads to 36 or less, and try again. 
Thanks for your attention.

**Comment by Xingyu-Liao** [comment]
Hi Wenda,

This problem may be caused by the unsuccessful installation of minimap2. Please review the installation log of minimap2 in path of '~/LongRepMarker_v2.0/log/minimap2_Install.log'. 

![QQ图片20220315122644](https://user-images.githubusercontent.com/60574102/158347650-11d301d6-9e36-43db-a2dd-f52ccca95469.png)


![QQ图片20220315122707](https://user-images.githubusercontent.com/60574102/158347658-286e6e30-2b68-4831-ad62-e65930f99097.png)

**Comment by Xingyu-Liao** [comment]
> Dear Dr. Liao： i am sorry to disturb， when i run java LongRepMarker -r ~/test-2021/10.resoult/genome_hic/final_Hic.fasta -o out -t 120
> 
> **occurred**
> 
> Step04: Finding overlap sequences between reference sequences / assemblies [ Time Cost: Error from Ref/Assembly detection mode: repDet2nd.Index: 0, Size: 0 java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 at java.util.ArrayList.rangeCheck(ArrayList.java:659) at java.util.ArrayList.get(ArrayList.java:435) at CoreModules.repDet2nd(CoreModules.java:110) at threadLTR.run(threadLTR.java:44) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
> 
> After monitoring for a period of time,about 4 hours，no longer commands running in **top** monitoring .
> 
> And，I found the **ovlp.paf** in the ~/LongRepMarker_v2.0-master/alignment is empty ，Is it related to it?
> 
> how can i do;any others information need? thanks for your reply! ![image](https://user-images.githubusercontent.com/77140740/158343422-d3d09269-7024-4c43-8526-d6db144899f5.png)


---------------------------------------------------

Hi Wenda,

This problem may be caused by the unsuccessful installation of minimap2. Please review the installation log of minimap2 in path of '~/LongRepMarker_v2.0/log/minimap2_Install.log'.

![QQ图片20220315122644](https://user-images.githubusercontent.com/60574102/158349118-d2a90e55-93f5-4254-900c-37b2fafda521.png)

![QQ图片20220315122707](https://user-images.githubusercontent.com/60574102/158349153-30c9c079-4cee-431d-9e1a-36c7b1a9b37d.png)

**Comment by zhangwenda0518** [comment]
Thanks for your quickly reply. 

**it is now working normally**

I checked the installation log. It is true that there was an error in the installation process of minimap2. 

I  then test manual installation minimap2   and  rerun   ./Makefile.sh     is    all   🆗

Thanks again for your answer.All the best for you！
